services:
  - type: web
    name: luxestay
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: PORT
        value: 8001
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        placeholder: "MongoDB Atlas Connection String"
      - key: ACCESS_TOKEN_SECRET
        generateValue: true
      - key: ACCESS_TOKEN_EXPIRY
        value: 1d
